services:
  web:
    build: .
    image: pcostas/filetransfer:latest
    container_name: filetransfer
    env_file: .env
    volumes:
      - ./db:/app/db
      - ./uploads:/app/uploads
    ports:
      - "3456:3000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    restart: always
